// my-svelte-app/src/Modal.svelte
<script>
    export let showModal = false;
    export let isPromo = false;
    export let message = '';
</script>

{#if showModal}
    <div class="backdrop" class:promo={isPromo} on:click|self> <!-- Event forwarding -->
        <div class="modal">
            <div>{message}</div>
            <slot></slot>
        </div>
    </div>
{/if}

<style>
    .backdrop {
        background: rgba(0, 0, 0, 0.8);
        width: 100%;
        height: 100%;
        position: fixed;
    }

    .modal {
        padding: 10px;
        border-radius: 10px;
        max-width: 400px;
        margin: 10% auto;
        text-align: center;
        background: white;
    }

    .promo .modal {
        background: crimson;
    }
</style>

// vue-app-router/src/components/Modal.vue
<template>
  <div v-if="showModal" class="backdrop" @click="handleClick">
        <div class="modal">
            <h1>Errors:</h1>
            <div></div>
            <slot></slot>
        </div>
    </div>
</template>

<script>
export default {
    props: ['showModal'],
    methods: {
        handleClick() {
            this.$emit('closeModal')
        }
    }
}
</script>

<style>
    .backdrop {
        background: rgba(0, 0, 0, 0.8);
        width: 100%;
        height: 100%;
        position: fixed;
        top: 0
    }

    .modal {
        padding: 10px;
        border-radius: 10px;
        max-width: 400px;
        margin: 10% auto;
        text-align: center;
        background: white;
    }
</style>
